import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/ui/Footer";

export const metadata = {
  title: "Disclaimer | ForgeFlow AI",
  description: "Disclaimer and architectural advice notices for ForgeFlow AI.",
};

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-[#070a14] text-[#f3f6fc] flex flex-col">
      <Navbar />

      <main className="flex-1 max-w-[900px] mx-auto px-6 pt-32 pb-20 space-y-8 text-xs md:text-sm leading-relaxed text-[#9aa4b8]">
        <div className="space-y-2 border-b border-[#1b2338] pb-6">
          <h1 className="text-3xl font-bold text-[#f3f6fc]">Disclaimer & Notices</h1>
          <p className="text-xs text-[#5c6980]">Last Updated: August 2026</p>
        </div>

        <section className="space-y-3">
          <h2 className="text-base font-semibold text-[#f3f6fc]">1. Architectural & Engineering Guidance</h2>
          <p>
            ForgeFlow AI uses automated algorithms and artificial intelligence to assist software planning. Recommendations generated by the platform (such as technology stacks, requirement lists, and component diagrams) are provided for informational and planning purposes only.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-semibold text-[#f3f6fc]">2. Verification & Validation</h2>
          <p>
            Users are encouraged to review, test, and validate all architectural blueprints, security policies, and technical specifications before deploying production software or committing infrastructure budgets.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-semibold text-[#f3f6fc]">3. Limitation of Liability</h2>
          <p>
            ForgeFlow AI and WarishLabs make no warranties, express or implied, regarding the absolute suitability of generated blueprints for specific enterprise environments or regulatory frameworks.
          </p>
        </section>

        <section className="space-y-3 border-t border-[#1b2338] pt-6">
          <h2 className="text-base font-semibold text-[#f3f6fc]">4. Contact Information</h2>
          <p>
            Reach out directly at{" "}
            <a
              href="https://warishlabs.in/contact"
              target="_blank"
              rel="noreferrer"
              className="text-[#38b6ff] underline"
            >
              WarishLabs Contact Page
            </a>.
          </p>
        </section>
      </main>

      <Footer />
    </div>
  );
}
