"use server";

import { auth } from "@clerk/nextjs/server";
import { revalidatePath } from "next/cache";
import { prisma } from "@/lib/db/prisma";
import { roadmapSynthesisNode } from "@/lib/ai/nodes/roadmapNode";
import { ActionResult } from "@/lib/actions/ai";

/**
  * Run Roadmap Synthesis to generate sequential milestone items
  */
export async function generateRoadmapAction(
  projectId: string
): Promise<ActionResult<{ success: boolean }>> {
  const { userId } = await auth();
  if (!userId) {
    return {
      success: false,
      error: { code: "UNAUTHORIZED", message: "Authentication required" },
    };
  }

  const startTime = Date.now();

  try {
    const project = await prisma.project.findFirst({
      where: { id: projectId, ownerId: userId },
      include: { features: true, decisions: true },
    });

    if (!project) {
      return {
        success: false,
        error: { code: "NOT_FOUND", message: "Project not found or access denied" },
      };
    }

    const projAny = project as any;
    const featuresList = projAny.features || [];
    const decisionsList = projAny.decisions || [];

    const synthResult = await roadmapSynthesisNode({
      projectName: project.name,
      ideaText: project.ideaText,
      features: featuresList,
      decisions: decisionsList,
    });

    await prisma.$transaction(async (tx) => {
      // Delete old roadmap items
      await tx.roadmapItem.deleteMany({
        where: { projectId },
      });

      // Create new roadmap items
      for (let i = 0; i < synthResult.items.length; i++) {
        const item = synthResult.items[i];
        await tx.roadmapItem.create({
          data: {
            projectId,
            title: item.title,
            phase: item.phase,
            status: item.status || "todo",
            order: i + 1,
            dependsOn: item.dependsOn || [],
          },
        });
      }

      // Update project status to EXPORTED / EXPORT_READY
      await tx.project.update({
        where: { id: projectId },
        data: { status: "EXPORTED" },
      });

      // Log AI Usage
      await tx.aiUsageLog.create({
        data: {
          projectId,
          operation: "roadmap",
          provider: process.env.LLM_PROVIDER || "groq",
          durationMs: Date.now() - startTime,
          status: "success",
        },
      });
    });

    revalidatePath(`/projects/${projectId}`);
    revalidatePath(`/projects/${projectId}/roadmap`);
    revalidatePath("/dashboard");

    return { success: true, data: { success: true } };
  } catch (error: any) {
    console.error("Error in generateRoadmapAction:", error);
    return {
      success: false,
      error: { code: "INTERNAL_ERROR", message: "Failed to generate roadmap milestones" },
    };
  }
}

/**
  * Export complete software blueprint as a formatted Markdown document
  */
export async function exportBlueprintMarkdownAction(
  projectId: string
): Promise<ActionResult<{ filename: string; content: string }>> {
  const { userId } = await auth();
  if (!userId) {
    return {
      success: false,
      error: { code: "UNAUTHORIZED", message: "Authentication required" },
    };
  }

  try {
    const project = await prisma.project.findFirst({
      where: { id: projectId, ownerId: userId },
      include: {
        features: true,
        decisions: true,
        roadmapItems: { orderBy: { order: "asc" } },
      },
    });

    if (!project) {
      return {
        success: false,
        error: { code: "NOT_FOUND", message: "Project not found or access denied" },
      };
    }

    const projAny = project as any;
    const decisionsList: any[] = projAny.decisions || [];
    const roadmapItemsList: any[] = projAny.roadmapItems || [];

    const reqObj = (project.requirements as { functional?: string[]; nonFunctional?: string[] }) || {};
    const functionalReqs = reqObj.functional || [];
    const nonFunctionalReqs = reqObj.nonFunctional || [];
    const stackList = Array.isArray(project.techStack) ? (project.techStack as string[]) : [];

    const archObj = (project.architecture as {
      overview?: string;
      components?: { name: string; type: string; description: string; tech: string }[];
      dataModels?: { entity: string; description: string; fields: string[] }[];
    }) || {};

    const markdown = `# ${project.name} — Technical Architecture & Implementation Blueprint

> Generated by **ForgeFlow AI Engine**  
> Status: \`${project.status}\`  
> Created: ${new Date(project.createdAt).toLocaleDateString()}

---

## 1. Executive Summary & Vision
${project.ideaText}

${project.problemStatement ? `### Problem Statement\n${project.problemStatement}\n` : ""}

---

## 2. Technology Stack
${stackList.length > 0 ? stackList.map((t) => `- **${t}**`).join("\n") : "Standard Next.js 16 + PostgreSQL stack"}

---

## 3. Requirement Synthesis

### Functional Requirements
${functionalReqs.length > 0 ? functionalReqs.map((r, i) => `${i + 1}. ${r}`).join("\n") : "No functional requirements recorded."}

### Non-Functional Requirements
${nonFunctionalReqs.length > 0 ? nonFunctionalReqs.map((r, i) => `${i + 1}. ${r}`).join("\n") : "No non-functional requirements recorded."}

---

## 4. System Architecture & Topology

${archObj.overview ? `### Topology Overview\n${archObj.overview}\n` : ""}

### System Components
${
  archObj.components && archObj.components.length > 0
    ? archObj.components
        .map(
          (c) =>
            `- **${c.name}** (\`${c.type}\`): ${c.description} *(Tech: ${c.tech})*`
        )
        .join("\n")
    : "Components not synthesized."
}

### Data Entity Models
${
  archObj.dataModels && archObj.dataModels.length > 0
    ? archObj.dataModels
        .map(
          (m) =>
            `#### Entity: ${m.entity}\n${m.description}\n- Fields: \`${m.fields.join("`, `")}\`\n`
        )
        .join("\n")
    : "Data models not synthesized."
}

---

## 5. Architecture Decision Records (ADRs)
${
  decisionsList.length > 0
    ? decisionsList
        .map(
          (d: any, i: number) =>
            `### ADR-${i + 1}: ${d.decision}\n- **Rationale**: ${d.reasoning}\n${
              d.alternative ? `- **Rejected Alternative**: ${d.alternative}\n` : ""
            }- **Impact Areas**: \`${(d.affectedAreas || []).join("`, `")}\`\n`
        )
        .join("\n")
    : "No ADRs recorded."
}

---

## 6. Implementation Roadmap & Delivery Milestones
${
  roadmapItemsList.length > 0
    ? roadmapItemsList
        .map(
          (item: any) =>
            `- [\`${(item.status || "todo").toUpperCase()}\`] **${item.title}** (Phase: \`${item.phase}\`)${
              item.dependsOn && item.dependsOn.length > 0
                ? ` — *Prerequisites: ${item.dependsOn.join(", ")}*`
                : ""
            }`
        )
        .join("\n")
    : "Roadmap items not scheduled."
}

---
*End of Blueprint — Synthesized autonomously by ForgeFlow AI.*
`;

    const sanitizeFilename = project.name.toLowerCase().replace(/[^a-z0-9]/g, "-");
    const filename = `${sanitizeFilename}-blueprint.md`;

    return {
      success: true,
      data: { filename, content: markdown },
    };
  } catch (error: any) {
    console.error("Error in exportBlueprintMarkdownAction:", error);
    return {
      success: false,
      error: { code: "INTERNAL_ERROR", message: "Failed to export blueprint markdown" },
    };
  }
}
